name: Solar App Deploy

on:
  push:
    branches: [ "staging", "main" ]
  pull_request:
    branches: [ "staging", "main" ]

jobs:
  deploy-staging:
    if: github.ref_name == 'staging'
    runs-on: ubuntu-latest
    environment: staging

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Deploy to Staging Server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ${{ secrets.APP_PATH }}
          git pull origin staging
          php artisan migrate --force
          php artisan optimize:clear
          php artisan cache:clear
          php artisan config:clear
          php artisan queue:restart

  deploy-main:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    environment: main   # create this env in GitHub and add prod secrets

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Deploy to Production Server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ${{ secrets.APP_PATH }}
          git pull origin main
          php artisan migrate --force
          php artisan optimize:clear
          php artisan cache:clear
          php artisan config:clear
          php artisan queue:restart
